apiVersion: v1
kind: Deployment
metadata:
  name: streamlit
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        build: ./streamlit
        ports:
        - containerPort: 8501
        env:
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: postgre-config
              key: postgre-url
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: postgre-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgre-secret
              key: postgre-password

---

apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: NodePort
  selector:
    app: streamlit
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30001